import mysql from 'mysql2/promise';
import dbConfig from '../dbConfig.js';

const data = [
  [1, 'Enthusiastic', 'S', 'S'],
  [1, 'Daring', 'Z', 'Z'],
  [1, 'Diplomatic', '*', '*'],
  [1, 'Satisfied', 'T', 'T'],
  [2, 'Cautious', '*', '*'],
  [2, 'Determined', 'Z', 'Z'],
  [2, 'Convincing', 'S', 'S'],
  [2, 'Good-natured', 'T', 'N'],
  [3, 'Friendly', 'S', 'N'],
  [3, 'Accurate', '*', '*'],
  [3, 'Outspoken', 'Z', 'Z'],
  [3, 'Calm', 'N', 'T'],
  [4, 'Talkative', 'S', 'S'],
  [4, 'Controlled', '*', '*'],
  [4, 'Conventional', 'T', 'T'],
  [4, 'Decisive', 'Z', 'Z'],
  [5, 'Adventurous', 'Z', 'Z'],
  [5, 'Insightful', '*', '*'],
  [5, 'Outgoing', 'S', 'S'],
  [5, 'Moderate', 'T', 'T'],
  [6, 'Gentle', 'T', 'T'],
  [6, 'Persuasive', 'S', 'N'],
  [6, 'Humble', 'N', '*'],
  [6, 'Original', 'N', 'Z'],
  [7, 'Expressive', 'S', 'S'],
  [7, 'Conscientious', '*', '*'],
  [7, 'Dominant', 'Z', 'Z'],
  [7, 'Responsive', 'N', 'T'],
  [8, 'Poised', 'S', 'S'],
  [8, 'Observant', '*', 'N'],
  [8, 'Modest', 'T', 'T'],
  [8, 'Impatient', 'Z', 'Z'],
  [9, 'Tactful', '*', '*'],
  [9, 'Agreeable', 'T', 'T'],
  [9, 'Magnetic', 'S', 'S'],
  [9, 'Insistent', 'Z', 'Z'],
  [10, 'Brave', 'Z', 'Z'],
  [10, 'Inspiring', 'S', 'S'],
  [10, 'Submissive', 'T', 'T'],
  [10, 'Timid', 'N', '*'],
  [11, 'Reserved', '*', '*'],
  [11, 'Obliging', 'T', 'T'],
  [11, 'Strong-willed', 'Z', 'Z'],
  [11, 'Cheerful', 'S', 'S'],
  [12, 'Stimulating', 'S', 'S'],
  [12, 'Kind', 'T', 'T'],
  [12, 'Perceptive', '*', '*'],
  [12, 'Independent', 'Z', 'Z'],
  [13, 'Competitive', 'Z', 'Z'],
  [13, 'Considerate', 'T', 'T'],
  [13, 'Joyful', 'S', 'S'],
  [13, 'Private', '*', '*'],
  [14, 'Fussy', '*', '*'],
  [14, 'Obedient', 'T', 'T'],
  [14, 'Firm', 'Z', 'Z'],
  [14, 'Playful', 'S', 'S'],
  [15, 'Attractive', 'S', 'S'],
  [15, 'Introspective', '*', 'N'],
  [15, 'Stubborn', 'Z', 'Z'],
  [15, 'Predictable', 'T', 'T'],
  [16, 'Logical', '*', '*'],
  [16, 'Bold', 'Z', 'Z'],
  [16, 'Loyal', 'T', 'T'],
  [16, 'Charming', 'S', 'S'],
  [17, 'Sociable', 'S', 'S'],
  [17, 'Patient', 'T', 'T'],
  [17, 'Self-reliant', 'Z', 'Z'],
  [17, 'Soft-spoken', '*', '*'],
  [18, 'Willing', 'T', 'T'],
  [18, 'Eager', 'Z', 'N'],
  [18, 'Thorough', '*', '*'],
  [18, 'High-spirited', 'S', 'S'],
  [19, 'Aggressive', 'Z', 'Z'],
  [19, 'Extroverted', 'S', 'S'],
  [19, 'Amiable', 'T', 'T'],
  [19, 'Fearful', 'N', '*'],
  [20, 'Confident', 'S', 'S'],
  [20, 'Sympathetic', 'T', 'T'],
  [20, 'Impartial', 'N', '*'],
  [20, 'Assertive', 'Z', 'Z'],
  [21, 'Well-disciplined', '*', '*'],
  [21, 'Generous', 'T', 'T'],
  [21, 'Animated', 'S', 'S'],
  [21, 'Persistent', 'Z', 'Z'],
  [22, 'Impulsive', 'S', 'S'],
  [22, 'Introverted', '*', '*'],
  [22, 'Forceful', 'Z', 'Z'],
  [22, 'Easygoing', 'T', 'T'],
  [23, 'Good mixer', 'S', 'S'],
  [23, 'Refined', '*', '*'],
  [23, 'Vigorous', 'Z', 'Z'],
  [23, 'Lenient', 'T', 'T'],
  [24, 'Captivating', 'S', 'S'],
  [24, 'Contended', 'T', 'T'],
  [24, 'Demanding', 'Z', 'Z'],
  [24, 'Compliant', '*', '*'],
  [25, 'Argumentative', 'Z', 'Z'],
  [25, 'Systematic', '*', '*'],
  [25, 'Cooperative', 'T', 'T'],
  [25, 'Light-hearted', 'S', 'S'],
  [26, 'Jovial', 'S', 'S'],
  [26, 'Precise', '*', '*'],
  [26, 'Direct', 'Z', 'Z'],
  [26, 'Even-tempered', 'T', 'T'],
  [27, 'Restless', 'Z', 'Z'],
  [27, 'Neighborly', 'T', 'T'],
  [27, 'Appealing', 'S', 'S'],
  [27, 'Careful', '*', '*'],
  [28, 'Respectful', '*', '*'],
  [28, 'Pioneering', 'Z', 'Z'],
  [28, 'Optimistic', 'S', 'S'],
  [28, 'Helpful', 'T', 'T']
];

async function populateAdjectives() {
  const connection = await mysql.createConnection(dbConfig);
  try {
    await connection.query('DELETE FROM adjectives'); // Clear existing data
    await connection.query('INSERT INTO adjectives (question_number, text, most_shape, least_shape) VALUES ?', [data]);
    console.log('adjectives table populated successfully.');
  } catch (err) {
    console.error('Error populating adjectives table:', err.message);
  } finally {
    await connection.end();
  }
}

populateAdjectives(); 